### Read data diffrent sources

In [2]:
import pandas as pd
from io import StringIO
Data = '{"employ_name":"James","email":"james@gmail.com","job_profile":[{"title1": "Team_leader"}]}'

df =pd.read_json(StringIO(Data))
df

  employ_name            email                job_profile
0       James  james@gmail.com  {'title1': 'Team_leader'}

In [3]:
df.to_json()

'{"employ_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team_leader"}}}'

In [4]:
df.to_json(orient='index')

'{"0":{"employ_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team_leader"}}}'

In [5]:
df.to_json(orient='records')

'[{"employ_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team_leader"}}]'

In [6]:
#  I access to the file using the browser
df =pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [8]:
# I just crat a folder by using to the (to)
df.to_csv("wine.csv")

In [ ]:
# Accessing the html file on web browser link

url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

pd.read_html(url)
# df[0]

In [ ]:
# wikipidia file to access it 

url ="https://en.wikipedia.org/wiki/Mobile_country_code"
df=pd.read_html(url,match="Country",header=0)[0]

HTTPError: HTTP Error 403: Forbidden

In [ ]:
df_excel =pd.read_excel('Cola.xlsx')

In [ ]:
df_excel.to_pickle('df_excel') # its be converting any file to convert pikkerl formattion

In [ ]:
pd.read_pickle('df_excel')

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
...,...,...,...,...,...,...,...,...,...,...,...,...
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945